module.exports = {
  REACT_APP_FIREBASE_KEY: 'INSERT KEY HERE',
  REACT_APP_FIREBASE_DOMAIN: 'INSERT DOMAIN HERE',
  REACT_APP_FIREBASE_PROJECT_ID: 'INSERT PROJECT ID HERE',
  REACT_APP_FIREBASE_STORAGE_BUCKET: 'INSERT STORAGE BUCKET HERE',
  REACT_APP_FIREBASE_SENDER_ID: 'INSERT SENDER ID HERE',
  REACT_APP_FIREBASE_APP_ID: 'INSERT APP ID HERE',
  LOCALTUNNEL: 'INSERT LOCAL TUNNEL URL HERE',
};